info: {}
paths:
  /products:
    get:
      description: |-
        Returns a list of products
        response:
        200: productsResponse
      operationId: listProducts
      tags:
      - products
swagger: "2.0"
